# Generated by Django 3.2.9 on 2021-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_name', models.CharField(choices=[('CTS', 'CTS'), ('BTC', 'BTC'), ('ETH', 'ETH')], default='CTS', max_length=4)),
                ('time', models.DateField(auto_now_add=True)),
                ('trade_volume', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_name', models.CharField(choices=[('CTS', 'CTS'), ('BTC', 'BTC'), ('ETH', 'ETH')], default='CTS', max_length=4)),
                ('current_value', models.IntegerField(default=0)),
                ('max_upper_bound', models.FloatField(blank=True, null=True)),
                ('min_lower_bound', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
