# Generated by Django 3.2.9 on 2021-11-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttrademodel',
            name='crypto_name',
            field=models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC'), ('CTS', 'CTS')], default='CTS', max_length=4),
        ),
        migrations.AlterField(
            model_name='cryptomodel',
            name='crypto_name',
            field=models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC'), ('CTS', 'CTS')], default='CTS', max_length=4),
        ),
    ]
