# Generated by Django 3.2.9 on 2021-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211129_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttrademodel',
            name='crypto_name',
            field=models.CharField(choices=[('CTS', 'CTS'), ('BTC', 'BTC'), ('ETH', 'ETH')], default='CTS', max_length=4),
        ),
        migrations.AlterField(
            model_name='cryptomodel',
            name='crypto_name',
            field=models.CharField(choices=[('CTS', 'CTS'), ('BTC', 'BTC'), ('ETH', 'ETH')], default='CTS', max_length=4),
        ),
        migrations.AlterField(
            model_name='cryptomodel',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
    ]
