# Generated by Django 3.2.9 on 2022-01-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220108_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousteademodel',
            name='default_trade_time',
            field=models.FloatField(default=2, verbose_name='estimated in hours'),
        ),
        migrations.AlterField(
            model_name='contracttrademodel',
            name='crypto_name',
            field=models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC'), ('CTS', 'CTS')], default='CTS', max_length=4),
        ),
        migrations.AlterField(
            model_name='cryptomodel',
            name='crypto_name',
            field=models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC'), ('CTS', 'CTS')], default='CTS', max_length=4),
        ),
    ]
